apiVersion: apps/v1
kind: Deployment
metadata:
  name: picframes
  namespace: memories
  labels:
    app: picframes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picframes
  template:
    metadata:
      labels:
        app: picframes
    spec:
      containers:
      - name: server
        image: ghcr.io/finn-e/picframes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: SHARE_DIR
          value: "/share"
        - name: CONFIG_DIR
          value: "/config"
        volumeMounts:
        - name: nfs-share
          mountPath: /share
        - name: config-volume
          mountPath: /config
      volumes:
      - name: nfs-share
        nfs:
          server: dahole.treee.house
          path: /frame-800x480-6colour
      - name: config-volume
        persistentVolumeClaim:
          claimName: picframes-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picframes-config-pvc
  namespace: memories
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: picframes
  namespace: memories
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: picframes
